### ISSUE TITLE
iOS opens urls in Safari (or Chrome), leaving the app

### ISSUE THREAD

**Issue by maggialejandro** [droibit/react-native-custom-tabs#8]
Hi. I don't know if it's the expected behavior but Android open a url without leaving the app while iOS open it on Safari (or Chrome), leaving the app. 

Is there any way to open a url in iOS without leaving the app? 

Thanks

**Comment by droibit** [comment]
Yes, it is expected behavior.

[Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs) only supports Android.
Therefore, On iOS uses a URL scheme to launch Chorme (or Safari), it behaves differently.

> Is there any way to open a url in iOS without leaving the app?

It might be possible to change the implementation to `SFSafariViewController`,   
but I will not implement it.
